version: "3.7"

services:
  db:
    image: postgres:12.1
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASES: >-
        tutorial_drf_db
    ports:
      - "5434:5434"

  tutorial-drf:
    container_name: "tutorial-drf"
    build:
      context: ./tutorial_drf/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./tutorial_drf/.env
    volumes:
      - ./tutorial_drf:/code

